services:
  ollama:
    build: .
    container_name: ollama
    image: ollama/ollama
    pull_policy: always
    healthcheck:
      test: ollama ps || exit 1
      interval: 10s
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    environment:
      # - OLLAMA_HOST='0.0.0.0'  # uncomment to make ollama reachable by other computers on your network
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_FLASH_ATTENTION=0 # 1 is experimental as of 0.3.11
    # If Ollama is not using the GPU, try  uncommenting those lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]